// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
// Prisma config typically handled in prisma/schema.prisma

export default {};
